<?php
/**
 * @author Ihor Ambrosov <ihor.ambrosov@gmail.com>
 * @license https://opensource.org/licenses/OSL-3.0
 */
?>
<?php $blockWrapper = $block->getWrapper(); ?>
<?php $blockWrapper->setObject($block); ?>

<?php if ($blockWrapper->isSplitOrder()) : ?>

<?php $orders = $blockWrapper->getOrders(); ?>
<?php if (!empty($orders)) : ?>
<ul class="orders print">
<?php foreach ($orders as $order) : ?>
<?php if ($blockWrapper->getCanViewOrder($order) && $blockWrapper->getCanPrintOrder($order)) : ?>
<li><a href="<?= $block->escapeUrl($blockWrapper->getPrintOrderUrl($order)) ?>" class="action print" target="_blank" rel="noopener">
    <?= $block->escapeHtml(__('Print receipt for order number: %1', $blockWrapper->getOrderId($order))) ?>
</a></li>
<?php endif; ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>
<?= $block->getChildHtml() ?>

<?php else : ?>

<?php $order = $blockWrapper->getOrder(); ?>
<?php if ($blockWrapper->getCanViewOrder($order) && $blockWrapper->getCanPrintOrder($order)) : ?>
<a href="<?= $block->escapeUrl($blockWrapper->getPrintOrderUrl($order) )?>" class="action print" target="_blank" rel="noopener"><?= $blockWrapper->escapeHtml(__('Print receipt')) ?></a>
<?= $block->getChildHtml() ?>
<?php endif; ?>

<?php endif; ?>